# Redis config
# This is a config for a relayer that covers gas for user transactions up to a allowance specified in Redis to interact with a whitelisted set of contracts.
# Allowances are on a per account id basis and on signup (account creation in redis and on-chain) an oauth token is required to help with sybil resistance

# Please note this is for reference only and you should be updating the values in the `config.toml` file found in the `pagoda-relayer-rs` directory.

# ip address to run server on, default to localhost
ip_address = [0, 0, 0, 0]
# port to expose
port = 3030
# replace with the account id of the public key you will use to sign relay transactions - this should match the account_id in your json file
relayer_account_id = "nomnomnom.testnet"
# this is a list of jsons from json key files containing 3 entries: account_id, public_key, secret_key
# NOTE: If you copy/paste the json from the key files, you might need to change private_key to secret_key
# NOTE: account_id for all keys used should match as they should be derived from the same account_id
# this is recommended for high throughput use cases to prevent nonce race conditions
keys_filename = "./account_keys/nomnomnom.testnet.json"
# whitelisted contract ids (receiver_id)
whitelisted_contracts = ["nomnomnom.testnet", "relayer_test0.testnet", "relayer_test1.testnet"]
# if this is set to false, just call /send_meta_tx or /relay endpoints. All other endpoints are coupled with using redis
# this needs to be set to true if use_fastauth_features = true
use_redis = true
# redis url for storing and retrieving allowance for an account_id and seeing if an oauth_token has been used before
redis_url = "redis://127.0.0.1:6379"

# set use_fastauth_features to true if you're integrating with fastauth -
# including check if sender id and receiver id are the same AND (AddKey or DeleteKey action) in process_signed_delegate_action fn
# and you're using shared storage contract
use_fastauth_features = false
# you can still use shared storage without fastauth features if you desire,
# but needs to be set to true if using fastauth or the contract you're sending transactions to requires a storage deposit
use_shared_storage = false

# Uncoment the network you want to use or add your own

# mainnet
# rpc_url = "https://rpc.mainnet.near.org"
# rpc_api_key = ""

# testnet
rpc_url = "https://rpc.testnet.near.org"
rpc_api_key = ""
